### ISSUE TITLE
Add "@reatom/persist" package

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#130]
Functionality:

- Persist state snapshot to storage
- Multiple storages (localStorage by default + API for adding storages)
- Configure interval or action to persist
- Configure partial atoms snapshot

**Comment by belozer** [comment]
> Configure interval or action to persist

Maybe needs use timeout (debounce)?

**Comment by artalar** [comment]
@belozer ++

**Comment by belozer** [comment]
Maybe you can connect it? https://github.com/rt2zz/redux-persist#basic-usage

**Comment by MaximMatsuk** [comment]
Is there any updates with this issue? or may be any example with connected redux-persist package?

**Comment by Akiyamka** [comment]
https://github.com/artalar/reatom/blob/d1cdd13c97f9fb62845b370ddd6dc772bbeb267d/packages/core/experiments/persist.ts
