### ISSUE TITLE
Add "vue" package

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#15]
[React package](https://github.com/artalar/reatom/tree/master/packages/react) may be used as a template

**Comment by lionskape** [comment]
I want to try to implement a solution for Vue2, but it can be a big performance leak in Vue3 if refs API will not be changed.

I wrote a comment in composition RFC, hopes that it will be resolved.

https://github.com/vuejs/rfcs/pull/78#issuecomment-544810237

**Comment by SeryiBaran** [comment]
Hello!

Vue package is not planned?
