### ISSUE TITLE
Need option for babel-plugin to generate strictly IDs

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#153]
I mean:

```ts
const myAtom = declareAtom(...)
// default --->
const myAtom = declareAtom('myAtom', ...)
// option on --->
const myAtom = declareAtom(['myAtom'], ...)
```

**Comment by belozer** [comment]
This is not safe and implicit behavior. Thus, the names of the atoms will conflict. 

I roughly understand your message (persist state), but me seems he not the right.

**Comment by belozer** [comment]
What about next behavior?

```js
const myAtom = declareAtom(...)
// default --->
const myAtom = declareAtom('myAtom', ...)
// option on --->
const myAtom = declareAtom(['myAtom.4da2edca'], ...)
```

```js
const myAtom = declareAtom(['<varName>.<pathTofileHash>'], ...)
```

**Comment by belozer** [comment]
But... What about this case?

```
const mySelector = (id) => {
  map(MyAtom, atom => atom[id])
}
```

**Comment by artalar** [comment]
Dynamic atom creation is a good point for collisions...
@Wroud can you (babel) generate strictly names only for top-level (in module - file) declarations and ignore declarations in user-scopes (functions)?

**Comment by belozer** [comment]
> But... What about this case?
> 
> ```js
> const mySelector = (id) => {
>   map(MyAtom, atom => atom[id])
> }
> ```

very cool, but a difficult decision.
```js
const mySelector = (id) => {
  map(['mySelector.' + id + '.abraCadabrHaSh' ], MyAtom, atom => atom[id])
}
```

**Comment by Wroud** [comment]
> Dynamic atom creation is a good point for collisions...
> @Wroud can you (babel) generate strictly names only for top-level (in module - file) declarations and ignore declarations in user-scopes (functions)?

It's possible i think
