### ISSUE TITLE
Add "@reatom/rx" package

### ISSUE THREAD

**Issue by ilyaryabchinski** [artalar/reatom#167]
Until Observable is not part of the ES spec, I suggest to add integration with [rxjs](https://github.com/ReactiveX/rxjs). Currently [rxjs](https://github.com/ReactiveX/rxjs) is an industry de facto standard for reactive programming.

What do you think, guys? Is it a good idea?

**Comment by artalar** [comment]
Sad that Rx is not used symbol-observable as "industry de facto standard"...
Anyway, I proposing that all integrations with any observables must be implemented in `@reactom/observable`. What current implementation of `@reactom/observable` missing for Rx? Can u PR changes?

**Comment by ilyaryabchinski** [comment]
> Sad that Rx is not used symbol-observable as "industry de facto standard"...

I think things will change when Observable finally becomes a part of ES spec.

Probably current implementation of `@reatom/observable` is not compatible with huge amount of rxjs pipable operators. Need to check it. If we implement this, It can be useful for users of  `reatom`.
