### ISSUE TITLE
Action type generic is not validating arguments

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#169]
Second generic must be valid only if _type_ set: `declareAction<any, 'action name'>([''action name''])`

![example](https://user-images.githubusercontent.com/27290320/66821420-10813680-ef4b-11e9-8935-2c6e16fef4fc.png)

**Comment by ilyaryabchinski** [comment]
@artalar could you please review my PR #171?

**Comment by artalar** [comment]
Fixed in `@reatom/core@1.0.0-rc18`

**Comment by artalar** [comment]
Fixed in `@reatom/core@1.0.0-rc18`
