### ISSUE TITLE
What is difference between reatom and other libs?

### ISSUE THREAD

**Issue by xgrommx** [artalar/reatom#201]
I have some experience with reactive programming (Rx, Bacon, Flyd, etc)
What is difference between join patterns with subjects from Rx?
What is difference between focal? (https://github.com/grammarly/focal)

As for me better solution is reactive join patterns (I hate redux with imperative constructions)

**Comment by artalar** [comment]
Thanks for your question!

All reactive libraries that you describe have two main problems:
1) State**ful** approach that forces you to think more about memory leaks. Atoms is state**less**, just like features ([example](https://github.com/fluture-js/Fluture)). It much reusable: define it once and reuse everywere (SSR is the main example).
2) Observables notify it child (subscribers) by [depth](https://en.wikipedia.org/wiki/Depth-first_search) that can generate glitches - it wastes performance and may spawn inconsistency... In Reatom atoms updates always ordered right and has no glitches.

> focal
Totaly different library about friendly reactive bindings to view (JSX-specific). Reatom is a framework-agnostic / any subscriber-agnostic state manager for efficiently calculate derived state and to give it away reactively.

**Comment by artalar** [comment]
@xgrommx I add the third problem after some thought

**Comment by xgrommx** [comment]
@artalar can u solve `Dining philosophers problem` in reatom via join patterns approach?

**Comment by xgrommx** [comment]
For example in Bacon.js exists `update` method. This is really correct version of join patterns in js libs about reactive programming
In Rx we can emulate it https://github.com/xgrommx/react-rx-flux/blob/master/src/rx-extensions.js
I most.js also we can do almost the same

**Comment by artalar** [comment]
> @artalar can u solve Dining philosophers problem in reatom via join patterns approach?
@xgrommx do you have some implementation by Rx or whatever, that I can try rewrite to Reatom?

**Comment by xgrommx** [comment]
@artalar Sure, https://baconjs.github.io/api.html#join-patterns-and-baconbus

**Comment by artalar** [comment]
@xgrommx sorry, maybe I don't understand the task completed, but it is resolution? https://codesandbox.io/s/reatom-diningphilosophersproblem-vdvv2

**Comment by xgrommx** [comment]
@artalar

Bacon variant

```
// philosopher 0 eating
// philosopher 0 thinking
// philosopher 2 eating
// philosopher 2 thinking
// philosopher 1 eating
// philosopher 1 thinking
// philosopher 0 eating
// philosopher 0 thinking
// philosopher 2 eating
// philosopher 2 thinking
// philosopher 1 eating
// philosopher 1 thinking
// philosopher 0 eating
// philosopher 0 thinking
// philosopher 2 eating
// philosopher 2 thinking
// philosopher 1 eating
// philosopher 1 thinking
```

Your variant

```
// philosopher 0 eating 
// philosopher 1 eating 
// philosopher 2 eating 
// philosopher 0 thinking 
// philosopher 0 eating 
// philosopher 1 thinking 
// philosopher 1 eating 
// philosopher 2 eating 
// philosopher 2 thinking 
// philosopher 0 thinking 
// philosopher 1 thinking 
// philosopher 2 thinking
```

**Comment by xgrommx** [comment]
@artalar this is simple example for join patterns (via `when`)
https://codepen.io/xgrommx/pen/qdyErQ

**Comment by BANOnotIT** [comment]
@xgrommx are you still interested? If so please create a topic in [Discussions.](https://github.com/artalar/reatom/discussions)
