### ISSUE TITLE
Use subscription instead of custom react implementation?

### ISSUE THREAD

**Issue by zmitry** [artalar/reatom#214]
Can we use official library https://www.npmjs.com/package/use-subscription for handing subscribers

**Comment by belozer** [comment]
I'm not sure, kind of not recommended to use. But this not accurately, need to do reserch on this issue.

![image](https://user-images.githubusercontent.com/1655916/67437593-dfaf9a00-f5f9-11e9-8376-243aa02d37ed.png)

**Comment by zmitry** [comment]
what are benefits of using custom implementation comparing to use-subscription?
