### ISSUE TITLE
Add script for bootstrap packages

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#285]
We need a script to create a folder in `/packages` for a new package with already predefined dot files, build and test scripts and etc

**Comment by dipiash** [comment]
Hi! Can you explain more information about task?

**Comment by evfleet** [comment]
I'd be willing to implement this, would it be possible to provide a mock env file to understand the variables that are needed and perhaps clarify what build/test scripts would be baseline for a new package?

**Comment by artalar** [comment]
Done by efb0c75a05a325f5aad94a0bbad6d8ac83bca11d
