### ISSUE TITLE
Add JSDoc

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#3]

**Comment by MrNoddyInfy** [comment]
I would like to take on this, can you tell me how to proceed and what exactly needs to be done. I am new to github.

**Comment by belozer** [comment]
@MrNoddyInfy hi! There is a small instruction on working with the code.

https://github.com/artalar/reatom/blob/master/CONTRIBUTING.md

**Comment by MrNoddyInfy** [comment]
Gone through the instructions. Can you help me to get started with task? What is expected in "Add JSDoc"?

**Comment by artalar** [comment]
@MrNoddyInfy I already write JSDoc for API of the core package: https://github.com/artalar/reatom/pull/213/files#diff-95c0c1844d51dbd531e91c35dee93cd0R47

But we still have no _examples_ section in JSDoc of `react` and `observable` packages, can you get it?
