### ISSUE TITLE
data in store changed without dispatching any actions

### ISSUE THREAD

**Issue by hronro** [artalar/reatom#303]
[CodeSandbox](https://codesandbox.io/s/reatom-bug-e9ngm)

Steps to reproduce in  this CodeSandbox demo:
1. In home page, add some todo lists
2. Click the "Go to 404 page" link to go to 404 page (this step doesn't trigger any reatom actions)
3. In 404 page, click "Back to home page" link to go to (this step doesn't trigger any reatom actions)
4. The data in home page has been reset to the initial state (which is unexpected)

It is so weird, I use the devtools to check the reatom store after step1, I found the store is correct at that time. But after some router changes (without dispatching any actions), the store has been changed...

**Comment by stenin-nikita** [comment]
After unmounting the component, the atoms are unsubscribed and the value in the store is cleared. There are two solutions to save the state between page transitions:

1) to subscribe on atom in parent component
```typescript
const App = () => {
  useAtom(todoListsAtom, () => null, [])

  return (
    <Router>
      <Home path="/" />
      <NotFound default />
    </Router>
  )
}

render(<Provider value={store}><App /></Provider>, rootElement);
```

2) to create store with initial atom

```typescript
const store = createStore(todoListsAtom)
```

**Comment by stenin-nikita** [comment]
Hmm. When using symbols as the name of an atom, the state is cleared too. I don't think it should be like this.

**Comment by foisonocean** [comment]
@stenin-nikita I tried solution 2 before, and I tried use Symbols or Strings as atom name, neither of them works. The solution 1 works for me as a workaround, but I hope we can have a better solution.

**Comment by artalar** [comment]
@foisonocean @stenin-nikita thx for it discussion! We must to do some improvements and I create issues for it.

**Comment by artalar** [comment]
#305 and #306 is solved. Remaining discussion should follow #304
