### ISSUE TITLE
support typescript 3.9

### ISSUE THREAD

**Issue by foisonocean** [artalar/reatom#336]
After upgrading TypeScript to v3.9.4, I got a lot type errors from reatom.

**Comment by binjospookie** [comment]
@artalar How can I help you with this issue? Have the same problem.

**Comment by artalar** [comment]
What kind of errors u have? Can u reproduce it with gitpod.io or something like it, please?

**Comment by binjospookie** [comment]
@artalar I create a repo with problem
https://github.com/binjospookie/reatom-ts-issue

How to reproduce:
* `npm run bootstrap`
* delete `@ts-ignore` comment at `packages/toussaint/index.ts`

For me error message looks like:
> Error:(12, 45) TS2345: Argument of type 'Action<number, string>' is not assignable to parameter of type 'Action<unknown, string>'.
  Type 'Action<number, string>' is not assignable to type '{ type: string; reactions?: Reaction<unknown>[] | undefined; }'.
    Types of property 'reactions' are incompatible.
      Type 'Reaction<number>[] | undefined' is not assignable to type 'Reaction<unknown>[] | undefined'.
        Type 'Reaction<number>[]' is not assignable to type 'Reaction<unknown>[]'.
          Type 'Reaction<number>' is not assignable to type 'Reaction<unknown>'.
            Type 'unknown' is not assignable to type 'number'.

**Comment by artalar** [comment]
Fixed at `@reatom/core@1.1.4`
