### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Tauka** [artalar/reatom#347]
Hi there! I noticed that last commit to the project was made almost month ago and latest release was published in January. Does this project have active maintainers?

Thank you

**Comment by artalar** [comment]
Hi! `@reatom/core@1*` is pretty stable, but still friendly to improvements and fixes, you can see it by [closed PRs](https://github.com/artalar/reatom/pulls?q=is%3Apr+is%3Aclosed).
[v1.1.0](https://github.com/artalar/reatom/releases/tag/v1.1.0) release is the last with new functionality, later releases includes only fixes.
