### ISSUE TITLE
Error occurs if unsubscribe from an atom before unsubscribe from depend an action

### ISSUE THREAD

**Issue by stenin-nikita** [artalar/reatom#348]
Step to reproduce:
- subscribe to the atom
- subscribe to an action
- unsubscribe from atom
- unsubscribe from an action

Example on [codesandobx](https://codesandbox.io/s/reatom-unsubscribe-bug-554zt?file=/src/index.ts)

**Comment by artalar** [comment]
Fixed at `core@1.1.5` 🔥
