### ISSUE TITLE
Cannot update state inside setInterval

### ISSUE THREAD

**Issue by defint** [artalar/reatom#351]
Hello
I have to change the atom value inside setInterval function. 

My first version of the code:
https://gist.github.com/defint/3faffb974ab76b1f7aa8adf0ff2ebadb 
It doesn't work.

My second version of the code with auto-clicking on the button:
https://gist.github.com/defint/fcf383dda69a934bfa411c2b89b72bc4
It works fine.

Can you please describe how to change the state without auto-clicking?

**Comment by artalar** [comment]
@defint thx for the issue, it a pretty weird thing, but I m sure your `App` wrapped into `React.StrictMode`. If you will try to remove `React.StrictMode` the bug will go. 
I still don't know why it happened, but let's keep this issue opened and I try to investigate and solve the bug a bit later.

**Comment by rrrshtt** [comment]
@artalar I found the problem, it lies in the way the react handles events. I will try to dive deeper into the topic, leave links that helped me.
https://github.com/facebook/react/issues/14259
https://github.com/pmndrs/zustand/issues/115
![image](https://user-images.githubusercontent.com/48245672/94685124-a0bdb480-0331-11eb-949a-ecf3eac83517.png)

**Comment by rrrshtt** [comment]
@defint quick solution for you
`useEffect(() => {
    setInterval(() => {
      ReactDOM.unstable_batchedUpdates(() => changeValue(Math.random()));
    }, 1000);
  }, []);`

**Comment by lkostrowski** [comment]
Additional info from me - I'm using action dispatchin on websocket event, effectively every second, I also didn't get updates and also was fixed by removing react strict mode

**Comment by artalar** [comment]
I will try to use `unstable_batchUpdate` + https://www.npmjs.com/package/use-subscription to fix this problem.
cc #214

**Comment by artalar** [comment]
Fixed at https://www.npmjs.com/package/@reatom/react/v/1.1.5
