### ISSUE TITLE
combine atoms not typed properly

### ISSUE THREAD

**Issue by lkostrowski** [artalar/reatom#353]
Using `combine` doesn't preserve type for combined members, both in tuple and record syntax

<img width="602" alt="Zrzut ekranu 2020-11-2 o 16 32 12" src="https://user-images.githubusercontent.com/9268745/97886571-0b934e80-1d29-11eb-9af1-2494d2bcc688.png">

If needed I will prepare reproduction

**Comment by artalar** [comment]
It is strange, I use it pattern often and haven't issues. Attach a reproduce pls.

**Comment by lkostrowski** [comment]
I extracted combine to a const first, now it works, hope it helps

<img width="794" alt="Zrzut ekranu 2020-11-2 o 18 15 32" src="https://user-images.githubusercontent.com/9268745/97897887-6764d400-1d37-11eb-84ab-67f497778d07.png">

**Comment by artalar** [comment]
It should work without extraction 🤔 what is TS version? By the way, TS CLI print the same issue or not (it is possible a WebShtorm issue)?

**Comment by lkostrowski** [comment]
Good point, indeed the problem is in Webstorm... I didn't check that right, because it failed compiling - but not because unknown, but nulls.

Anyway, closing, thanks for quick response.
