### ISSUE TITLE
Api proposal for the next major version of reatom

### ISSUE THREAD

**Issue by stenin-nikita** [artalar/reatom#354]
# Introduction

The purpose of proposal is to refuse to create actions. The idea is to better focus on the business logic of the app and write less code. 

# List of proposal
- Divide into computed and leaf atoms
- Batch updates out of the box
- New and simple user API

An example can be found [here](https://gist.github.com/stenin-nikita/e7754e3504c1cf146e98f8dd095b53cb#file-reatom-proposal-api-ts)

**Comment by artalar** [comment]
A lot of work is ended in `v2` branch.

**Comment by artalar** [comment]
![image](https://user-images.githubusercontent.com/27290320/129205394-203cc713-5dfb-44d0-a884-c82f0e15de05.png)
