### ISSUE TITLE
reatom / react > 1.1.1 useAtom doesn't update state

### ISSUE THREAD

**Issue by vadeneev** [artalar/reatom#356]
It simply doesn't want to work with > 1.1.1 -> you could check simple setup here
https://codesandbox.io/s/reatomasynctodo2-forked-igb1h?file=/src/components/TodoList/TodoList.jsx

**Comment by on3dd** [comment]
Same, I just spent a few hours looking for possible errors to realize that the component using useAtom just didn't notice the asynchronous changes 😕

**Comment by artalar** [comment]
See #351 please
