### ISSUE TITLE
Reatom React guide broken

### ISSUE THREAD

**Issue by TheLogan** [artalar/reatom#358]
Hi I'm trying my hand with Reatom to see if I can use it for my current project, and couldn't get the react guide to work, here are my steps:
I created a clean react project using CRA, I then copy pasted the code from
https://reatom.js.org/#/packages/react?id=usage
into the project (replacing the code in app.tsx and creating a new file called Form.tsx in /components/)

First of all this complains, 
`on(changeName, (state, payload) => payload)`
payload seems to be undefined but on is expecting a string, I can fix it by just giving the payload an any type
Further down there's another error
`const handleChangeName = useAction(e => changeName(e.target.value))`
Here ChangeName expects 0 arguments but is being given one anyway, I tried silencing it by telling TS to ignore the line.
But it really really really does not want any arguments, and so when I tried to run the project it broke down. 
If I remove the input then it finally does run, but the moment I try to write anything in the input field I get another breaking error:

> Error: [reatom] Invalid state. Reducer number 1 in "atom [2]" atom returns undefined

**Comment by meff34** [comment]
All you need to do is pass the type-parameter in the `declareAction` call like this

```typescript
const changeName = declareAction<string>();
//                              ^^^^^^^^
```

Check out [this sandbox](https://codesandbox.io/s/optimistic-galileo-ptp3b?file=/src/components/Form.tsx)

**Comment by artalar** [comment]
https://codesandbox.io/s/reatom-example-285-15s7o
