### ISSUE TITLE
Add simple step-by-step examples

### ISSUE THREAD

**Issue by kolebayev** [artalar/reatom#359]
Hi. Please add step by step example for getting started with Reatom. [Something like this](https://easy-peasy-v3.now.sh/docs/quick-start.html#quick-start)

**Comment by artalar** [comment]
Personally, I am focused on advanced examples, like SSR (next.js), reusable instances and etc, and work on it in my free time. But simple introduction examples are needed too, ofc and I hope I will find some time for that a little bit later.
If somebody wants to take this issue, I want to propose ends this example: https://github.com/artalar/rtk-github-issues-example/pull/1

**Comment by BANOnotIT** [comment]
I would say https://github.com/artalar/rtk-github-issues-example/pull/1 is kinda outdated as well as this issue.

I think instead we should create some section in guides dedicated to such examples for different frameworks.
