### ISSUE TITLE
Replace husky by simple-git-hooks

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#360]
Add:

- [x] simple-git-hooks
- [x] commitlint
- [ ] `lint-staged` for prettier

**Comment by JeremyTechDev** [comment]
Heey, can I get this issue assigned to me? Want to participate in Hacktoberfest

**Comment by shameondev** [comment]
Looks like it is closed for now... @artalar

**Comment by artalar** [comment]
I just fixed the description, the last missed task is `lint-staged for prettier`
