### ISSUE TITLE
Not work in react-native

### ISSUE THREAD

**Issue by BataevDaniil** [artalar/reatom#365]
Reatom have in peerDependencies react-dom. I want to have not binding to react-dom

**Comment by artalar** [comment]
Khm, good question...
React@18 incudes needed features and don't require react-dom any more. So I may publish a next majore version of the reatom/react package with react@18 in requirements. But I can't do it becouse the the next version already employed by _the next majore version_ with new features (reatom/core@2).

I need more time to investigate this problem.

**Comment by BataevDaniil** [comment]
Я suppose the issue can be solved by adding a separate reactive-native file and linking its in package.json as followed: https://github.com/styled-components/styled-components/blob/main/packages/styled-components/package.json#L7. This file will conclude temporary fix for react-native.

Currently, I have to mock react-dom with local library containing only one function which just invokes everything what was passed to it.
````js
exports.default = {
  unstable_batchedUpdates: (f) => {
    f();
  },
};
````
I'm worried to use that way because it definitely can lead to some bugs.
What do you think of that temporary solution?
I can create a PR if you don't mind.

Thank you for your activity)

**Comment by artalar** [comment]
Probably yes, thx for example link. I try to fix it tomorrow.

**Comment by artalar** [comment]
@BataevDaniil sry, I was inattentive at the last time.

> What do you think of that temporary solution?

It is ok.

> I can create a PR if you don't mind.

I will really pleasure for it.

> Thank you for your activity)

Thanks for your report and solution suggestion.

Also, check this out https://github.com/alloc/react-batched-updates

**Comment by BataevDaniil** [comment]
Solution work for reatom v1 and [here](https://github.com/artalar/reatom/pull/377) solution for reatom v2
