### ISSUE TITLE
takeLatest for effects?

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#368]
Is it possible to emulate [takeLatest ](https://redux-saga.js.org/docs/api/#takelatestpattern-saga-args) behavior by effects?

**Comment by BataevDaniil** [comment]
Is it just debounce?

**Comment by artalar** [comment]
debounce delay function start, takeLatest skip function result

**Comment by artalar** [comment]
Done by `withAbort` and automatic `AbortController` subscribtion
