### ISSUE TITLE
Generalize ref pattern into util package

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#371]
[Here](https://github.com/artalar/reatom/tree/v2/packages/core#increase-performance-by-ref-pattern) described a pattern of how to manage (change dynamicaly) huge lists of coupled elements. [The example](https://github.com/artalar/reatom2-lists-example) includes worked code, but looks boilerplate, it will be good to wrap lists \ elements creation and linking to a specific fabric, like:

```ts
const {users, roles} = createEntities({users: { key: 'name' }, roles: { key: 'name' } })
```

**Comment by BataevDaniil** [comment]
link 'Here' not relevant. Is this issue relevant? @artalar
