### ISSUE TITLE
Add tests for decorators

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#375]
[Experiments](https://github.com/artalar/reatom/tree/v2/packages/core/experiments) includes a few decorators (type `AtomDecorator`). To move it in separate stable packages we need tests with full test coverage.

**Comment by masihtamsoy** [comment]
Hi, can I pick this up?

**Comment by artalar** [comment]
Hi! We already have tests for `debounce` and `memo`, but have no tests for `createPersist`, could you get this one?

**Comment by masihtamsoy** [comment]
Sure, will do. Is there anything to consider before starting? @artalar

**Comment by artalar** [comment]
@masihtamsoy we need to test a few edge cases around the options:

- [ ] `throttle` save value even dispatch was two \ three times with last in the throttle time
- [ ] `get` and `set` use an atom **id** if a key (optional _persist_ argument) is not passed

The main test workflow is:

- create test _persist_ from `createPersist` with focus on some scope variable with a type `Record<string, any>`
- create atoms (from `createAtom` AND `createPrimitiveAtom` or `createNumberAtom`) with the above decorator, create a store, dispatch something, check the scope variable equality to expected values
- create a new store, getState from it the created atoms, and receives states from the record.

**Comment by masihtamsoy** [comment]
Ok will look into it. @artalar 

Need help, I am setting reatom locally. How to run all tests that already exist. Besides, if I only want to run test files in experiments folder; scripts that will help me do so (I tried running `npm run prepublishOnly`: not work for me) ? Didn't found any documentation.

**Comment by artalar** [comment]
Sory, we in the progress of migration our infrastructure.., missed docs is my fault.

You need npm v7, `npm i ` in the repo root, `npm run build` in the core package and `npm run test` / `npm run test-experiments`

**Comment by masihtamsoy** [comment]
Thanks @artalar  got it setup and running.

I can check on the issue now. Do you have any resource to refer, that you think can help me? Do share, thanks.

**Comment by artalar** [comment]
You may check `packages/core/experiments/debounce.test.ts`, which includes work with a store and `mockFn`.

**Comment by masihtamsoy** [comment]
@artalar Sorry, I didn't get what `mockFn` do? Can you briefly explain its scope.

**Comment by artalar** [comment]
@masihtamsoy, it is a simple wrapper for function which allow you to inspect the function calls

**Comment by artalar** [comment]
not actual as v3 already close to release
