### ISSUE TITLE
Types after build are broken

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#381]
<img width="876" alt="CleanShot 2021-10-01 at 13 10 42@2x" src="https://user-images.githubusercontent.com/27290320/135603296-1ce1a7f7-ae8b-4a07-a28a-d9006c23bb04.png">

**Comment by JeremyTechDev** [comment]
Heeey! I'd like to get this one assigned to me pls 🙌

**Comment by artalar** [comment]
O, awesome)

Take your attention that this bug relative to the `v2` branch!

**Comment by artalar** [comment]
Isn't important anymore, as I understand.
