### ISSUE TITLE
Move all code from index

### ISSUE THREAD

**Issue by BataevDaniil** [artalar/reatom#391]
Move code from index to entity file and type in index only export from internal module

**Comment by BANOnotIT** [comment]
I guess we need some kind of eslint-plugin or something that'll give notification "this file have too many functions, please split it into several files"

**Comment by artalar** [comment]
I start doing it for some packages

**Comment by BANOnotIT** [comment]
@artalar don't you think creating a eslint rule that limits index.ts files contents will speed this process up a little bit?

**Comment by artalar** [comment]
Nope :)

Currently we need to refactor only async/src/index.ts, the core package need to be in one file as it handy for me and nobody else will play with this code
