### ISSUE TITLE
Any devtools for v2?

### ISSUE THREAD

**Issue by kompolom** [artalar/reatom#398]
Its, really important to have convenient devtools for store debug. Reatom v1 can connect to redux devtools and it is cool.  What about v2? How to inspect store state?

**Comment by artalar** [comment]
Hi! Here it is https://gist.github.com/artalar/6629053e66e331c11331b8a895941647

I will publish it is a package soon

**Comment by kompolom** [comment]
And how to connect defaultStore?

**Comment by artalar** [comment]
@kompolom you can do it so now:
```
import { defaultStore } from '@reatom/core'
import { connectReduxDevtools } from '@reatom/redux-devtools'

connectReduxDevtools({ store: defaultStore })
```
