### ISSUE TITLE
Add new npm package ` @reatom/npm-history`

### ISSUE THREAD

**Issue by tamrazov** [artalar/reatom#422]
Add new npm package ` @reatom/npm-history` in packages. This package will be based on [history](https://www.npmjs.com/package/history)

**Comment by BataevDaniil** [comment]
Great idea! But I suggest making @reatom/router based on lib history. And after @reatom/react-router with interface same https://v5.reactrouter.com/web/guides/quick-start

**Comment by tamrazov** [comment]
I think it's a good idea, I'll do it soon.

**Comment by artalar** [comment]
I will write about our new naming conventions. Base idea is use `npm-*` for any library wrapper and `web-*` for web api wrapper (and `*-*` for some other context, like **node** or **RN**)

**Comment by BANOnotIT** [comment]
@artalar I see `packages/npm-history` code. Does it's presence mean that this issue is resolved?

Also it might be better to make `npm-*` and `web-*` more verbose in documentation so that scope is obvious.

**Comment by artalar** [comment]
Done
