### ISSUE TITLE
Horizontal scroll in docs

### ISSUE THREAD

**Issue by romadryud** [artalar/reatom#436]
Hi, docs have horizontal scroll, I believe it's not suppose to be there.

Screenshot: 
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/19193036/199115334-173cb2a5-d2bd-499f-88e7-bb59bfda51e2.png">

Workaround
Quick fix it's removing `min-width: min(calc(100vw + 20rem), 85rem);` from `body.mono, body.mono-all, .mono-all body`.

**Comment by artalar** [comment]
It should be synced with [this](https://github.com/artalar/reatom/blob/v3/docs/public/styles/mono.css#L95) 

🤔 Duno why it doesn't work properly, any thoughts?

**Comment by romadryud** [comment]
@artalar Also it appearing when width of the screen is < 1228px and fixing by changing to `84rem`. In some point responsiveness are gone. I can try to fix.

If you try to change `width: min(100vw, 65rem);` for main it will not effect horizontal scroll.

**Comment by artalar** [comment]
Would love to see PR 👍

**Comment by crashmax-dev** [comment]
@artalar outdated
