### ISSUE TITLE
Fix mobile view for docs site

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#445]
There is a couple of issues for iOS and the weight of the main content is not always `100vw` (sometimes bigger). Please note, that the horizontal scroll and sidebar overflow is intended behavior.

[reatom.dev](https://www.reatom.dev)

**Comment by Guria** [comment]
Just tested on iPhone 7 (iOS 15.7). Main content is correct size, but I'm unable to use sidebar menu. Whenever I scroll to it viewport jumps back to main content.

**Comment by crashmax-dev** [comment]
@artalar outdated
