### ISSUE TITLE
How to run action on component's props change?

### ISSUE THREAD

**Issue by vovanezha** [artalar/reatom#449]
I have an async function wrapped in `reatomAsync`:

```javascript
const fetchProgress = reatomAsync((ctx, category: string) => 
  fetchProgress(...)
    .then(data => progressAtom(data))
    .catch(handleError)
);

```

And a component that takes `category` as a prop. So I want to call an action on every prop change. 

What to come in my mind is to use `useEffect`:

```javascript
const Component = ({category}) => {
  const [progress] = useAtom(progressAtom);
  
  useEffect(() => fetchProgress(category), [category]);

  return ...;  
}
```

But I'd like to escape useEffect usage somehow, if it possible. Is there any recommendations of how to handle such cases?

**Comment by artalar** [comment]
@vovanezha yep, [something like that](https://www.reatom.dev/packages/async#periodic-refresh-for-used-data)

**Comment by artalar** [comment]
Hmm, you have a payload for the fetch from props? Don't know how it even possible without `useEffect`. But if you these `category` in an atom, just use `onConnect(progressAtom, ctx => fetchProgress(ctx.get(categoryAtom)))`.

**Comment by vovanezha** [comment]
Got it, thanks for quick answer

**Comment by artalar** [comment]
Just curious, how you solved it finally?)
