### ISSUE TITLE
@reatom/undo: add the possibility of aggregating the history of several atoms

### ISSUE THREAD

**Issue by mule-stand** [artalar/reatom#461]
Add the ability to navigate through the change history of not only one atom, but the combined history of several atoms

**Comment by BANOnotIT** [comment]
@mule-stand would you mind to give some examples of how this can work for you. Any business cases?

**Comment by BANOnotIT** [comment]
I'm wondering if creating an atom with `combine(...atoms)` would work?

**Comment by artalar** [comment]
`reatomUndo` added! https://www.reatom.dev/packages/undo
(previously there was only `withUndo`)
