### ISSUE TITLE
Cursor should be pointer on hover sidebar links

### ISSUE THREAD

**Issue by Starboy-Sharma** [artalar/reatom#468]
- If you hover on the sidebar guides/general then our cursor should be a pointer
![image](https://user-images.githubusercontent.com/31812684/217631215-d96f7c29-d474-4e0e-a04b-4ae48c854566.png)

- Also if you hover over the sublinks cursor should be a pointer on the icon As a user I should be able to click on the text or the list style icon and should be redirected to the respective page.

**Comment by BANOnotIT** [comment]
Fixed in https://github.com/artalar/reatom/pull/495/commits/3d7cd6c8caae364d9e4396fde14d2e3c402ae4bd
