### ISSUE TITLE
withCache throws maximum call stack size exceeded

### ISSUE THREAD

**Issue by crashmax-dev** [artalar/reatom#486]
I took this [example](https://codesandbox.io/s/reatomasync-9t0x42?file=/src/model.ts) and added withCache [here](https://github.com/crashmax-dev/awesome-nextjs/blob/master/src/features/profile/model.ts#L30)
Why this is happening?

**Comment by artalar** [comment]
Hi! Will look at this today.
Btw, right now we do not have a build in solution for SSR, but Reatom design is friendly for this, I will publish some helpers in this week.

**Comment by artalar** [comment]
Fixed!
