### ISSUE TITLE
withCache does not update statusesAtom

### ISSUE THREAD

**Issue by vovanezha** [artalar/reatom#489]
### Description:

If using `withStatusesAtom` and `withCache` together and if data was taken from cache, `statuesAtom` won't be updated and always returns `isPending: true`

### Reproduction link:

https://codesandbox.io/s/withcache-issue-forked-hnilwu

**Comment by vovanezha** [comment]
@artalar hey! the issue is still there with `@reatom/framework@3.2.0` version. Moreover there are new additional issues:

1.  `pendingAtom` is always `1` if `withCache` specified
2.  `Cannot create property 'toString' on number '34'` error in console

Reproduction link — https://codesandbox.io/s/withcache-issue-forked-hnilwu

**Comment by artalar** [comment]
@vovanezha hey! The 'toString' error fixed! The behaviour of `pendingAtom` is expected, as cache trying to cache calls - https://github.com/artalar/reatom/blob/8a88b020069a0e667a0f0b88dce987fea5a48a19/packages/async/src/withCache.test.ts#L114-L115
