### ISSUE TITLE
Name uniqueness validator

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#493]
We need a tool to validate atoms and actions names uniqueness. It easy to implement - just parse logs (`ctx.subscribe(logs => ...)`) and throw an error, if some name (`log.proto.name`) is doubled. But there are two advantage:

- how to store previously created names and not leak memory
- how to handle dynamically recreated atoms, like by atomization and API invalidation

**Comment by BANOnotIT** [comment]
> how to handle dynamically recreated atoms, like by atomization and API invalidation

I believe there might be some trick with WeakMap that can help with this problem.
