### ISSUE TITLE
Remove UMD output target from builds

### ISSUE THREAD

**Issue by BANOnotIT** [artalar/reatom#502]
Currently many packages have dependencies on other projects. No global names are defined in package.json thus microbundle is forced to _guess_ names for global variables that'll hold module in UMD. It's internal algorithm may work for packages defined inside this repo (but auto-guessed `globalThis.core` which is @reatom/core is discussable). Some packages don't have any UMD at all and microbundle is forced to guess global names for dependencies. That's how useSyncExternalStorage becomes accessible by `globlThis.shim.useSyncExternalStorage`.

I propose remove UMD target at all since it never was promoted in documentation and most likely all builds are simply broken.

https://github.com/artalar/reatom/actions/runs/4415832365/jobs/7739801803#step:5:432

**Comment by artalar** [comment]
done
