### ISSUE TITLE
Make `turbo run test` work stabely

### ISSUE THREAD

**Issue by BANOnotIT** [artalar/reatom#504]
Right now CI workflow brokes on testing stage with random package. Same problem can be reproduced by running `npm run test` in repository without `npm run build` before and even on first `run test` sometimes it breaks.

**Comment by BANOnotIT** [comment]
https://github.com/artalar/reatom/actions/runs/4441812439/jobs/7797343508?pr=510

**Comment by artalar** [comment]
Looks like all fine now
