### ISSUE TITLE
Use local fonts instead of google

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#522]
https://github.com/artalar/reatom/blob/2e03ec68ba00ff564967a7fac822691754206c21/docs/src/layouts/Layout.astro#L40

**Comment by BANOnotIT** [comment]
You want something like https://fontsource.org/?

**Comment by BANOnotIT** [comment]
Btw do you have any argumentation why you don't like google hosting for them? I some rationale of this decision?

**Comment by artalar** [comment]
@BANOnotIT handshake with other domain is redundant, also it is open for Google some tracking abilities.

**Comment by BANOnotIT** [comment]
So you're not concerned about vercel giving same and even more tracking abilities?

I mean vercel can and vercel do inject js in sites that are hosted on it.

It's up to you obviously to decide which companies are more risky for your audience but I don't really get this rationale. It just don't match up in my head.
