### ISSUE TITLE
docs:  Incorrect parameter order in onEffect example

### ISSUE THREAD

**Issue by skhrv** [artalar/reatom#525]
There is an error in the documentation for the reatomAsync function. The order of the parameters params and promise in the onEffect hook is incorrect. 

The current example provided in the documentation is:
```ts
onEffect(ctx, promise, params) {
  listAtom(ctx, { data: [], status: 'pending' })
},
```

The correct order of the parameters should be:
```ts
onEffect(ctx, params, promise) {
  listAtom(ctx, { data: [], status: 'pending' })
},
```

Please update the documentation to reflect the correct order of the parameters to prevent confusion for users working with the reatomAsync function.

**Comment by artalar** [comment]
Fixed. Also, you could now get `params` from `onUpdate` too!

![image](https://user-images.githubusercontent.com/27290320/230911166-39f05256-b932-4a69-9fa3-3b20fa77e1ab.png)
