### ISSUE TITLE
Add the context name to the logger

### ISSUE THREAD

**Issue by skhrv** [artalar/reatom#542]
It would be useful to add the context name to the logger, in cases where multiple contexts exist and need to be distinguished in the console. Similar functionality exists in Redux DevTools: https://github.com/reduxjs/redux-devtools/blob/main/extension/docs/API/Arguments.md#name

**Comment by artalar** [comment]
Done https://github.com/artalar/reatom/commit/e09b4a65cbfb2bbf0e3559f1c3518622f688db48
