### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#555]
We plan to release a new major version each year. ~~**No heavy breaking changes**, only improvements around some quirks of existed API.~~ We found a way to hide `ctx` and make the code more natural. This is the most required feature and we glad to be able to implement it fast as possible. Many features of reatom/effects and reatom/async will be integrated to the core package for better performance and less complex realization, it will be allow you to use `withCache` for regular atoms and actions, which is unbelivable cool. But we will try to not change things a lot: `atom`, `action`, `pipe`, `onChange`, `onCall` will the same, as many other APIs.

Here is the list of notes what we should to change.

- [ ] remove `AtomCache` from the third argument of `onUpdate` callback. Pass `params` to the third argument of `onUpdate` callback.
- [ ] remove **optional** `spy` method from `Ctx` (it should have no any effect for existed code)
- [ ] change `ctx.spy(({ params, payload }) => )` to `ctx.spy((params, payload) => )`
- [ ] some guarantees of uniqueness of names #556 
- [ ] do not call callback from the second argument of `ctx.spy` for atoms on initiate
- [ ] prevent `subscribe` from `onConnect` to prevent connection stack
- [ ] made return type of `callSafely` is `void`
- [ ] throw an error if `with*` (mutable) operator applies multiple times
- [ ] replace [unstable_fn](https://github.com/artalar/reatom/blob/8cfc32849cd178fb2e3ccbe340e5bac3df1c158d/packages/core/src/atom.ts#L689) by something public and less hacky, maybe optional `mock` method?
- [ ] drop `AsyncOptions` hooks to force `onUpdate` using for consistent codestyle
- [ ] remove `abortControllerAtom` as a public property of `AsyncAction` coz in mostly internal thing, which behaviour could be not obvious for a user
- [ ] use native `throwIfAborted` instead of ponyfil from the utils
- [ ] `withReducers` should accept `ctx` by the first argument
- [ ] remove `ctx.get(callback)` API and and explicit `batch` API or allow to delay updates to a next tick for autobatching
- [ ] remove `null` variant from `AtomCache['cause']`
- [ ] `dataAtom.reset` should return the last (not new) state, to use it for a rollback
- [ ] move `bind` from reatom/lens to ... something else.
- [ ] `getRootCause` should accept `Ctx` and the realisation should be just `ctx.get(read => read(__root)!)`
- [ ] `ctx.controller` should be removed, the feature will be replaced with instence of `CauseContext`
- [ ] infer error type from field validation (reatom/form)
- [ ] remove `after` optional parameter from `retry` of `withRetry`
- [ ] `withRetry` should wrap returned promise which shouldn't fail during retrying

**Comment by BANOnotIT** [comment]
- [ ] Make types for atom reducers https://github.com/artalar/reatom/pull/518
- [ ] Define in docuemntation if `atom(..., <name>)` should be have globally unique hand written ID or it should be just debug name #556

**Comment by artalar** [comment]
This issue contains a list on minor changes, which is not so relevent anymore, as we want to change a little bit more: https://github.com/artalar/reatom/issues/841
