### ISSUE TITLE
How to track names uniqueness?

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#556]
One of the main priority of Reatom is the best debug experience. A state management hard as itself and it is important to think about this as a default feature, which should be integrated in all other features.

One of the important and difficult by default feature of debuggability is a state identification. We should provide reach (sound) names for all atoms and actions, but how to grant their uniqueness?

We need a tool to validate atoms and actions names uniqueness. It easy to implement - just parse logs (`ctx.subscribe(logs => ...)`) and throw an error, if some name (`log.proto.name`) is doubled. A couple important notes:

- to prevent memory leaks we should use `Map<string, AtomProto>` (`string` is a name) **AND** `FinalizationRegistry`
- we have a conversion that dynamically created names includes `#${id}` pattern - this kind of atoms could be doubled 🤔

**Comment by BANOnotIT** [comment]
https://github.com/artalar/reatom/issues/493

**Comment by artalar** [comment]
We don't need that. Eslint with domain handling should be enoght.
