### ISSUE TITLE
TypeScript compile option `moduleResolution` in the `bundler` value causes an error `TS7016: Could not find a declaration file for module '@reatom/*`

### ISSUE THREAD

**Issue by mule-stand** [artalar/reatom#560]
TypeScript compile option `moduleResolution` in the `bundler` value causes an error `TS7016: Could not find a declaration file for module...` when importing `@reatom/framework`, `@reatom/npm-react` packages.

**Comment by artalar** [comment]
How could I reproduce it?

**Comment by BANOnotIT** [comment]
@artalar you should use pnpm I guess for that

**Comment by artalar** [comment]
Sooo, why the problem is in Reatom? I'm not a pro in this package management stuf, will hope somebody could help with it.

**Comment by BANOnotIT** [comment]
We don't expose `"exports": { "types": "./build/index.d.ts" }`
