### ISSUE TITLE
change links from repl to csb

### ISSUE THREAD

**Issue by ptrtorain** [artalar/reatom#562]
can you please change your links to codesandbox? repl doesn't load a page for me, I get an empty page.

**Comment by BANOnotIT** [comment]
Can you point out which links and where do not work for you?

**Comment by ptrtorain** [comment]
> Can you point out which links and where do not work for you?

https://www.reatom.dev/ main page has 3 links to repl, after loading these templates I get blank page. Can you add codesandbox? Replit is always low on resources and lagging everytime. Thanks!

**Comment by artalar** [comment]
I agree, I have an issues with replit too (and with stackblitz). I would be appreciative of your contribution, but I should be the owner of the sandboxes to have ability to manage it in the feature.

If you have some advanced examples you could share it as a github repo, to make it possible to propose some feature changes by a PR. We could add this kind of links to examples page too.

I will rewrite the current links today.

**Comment by ptrtorain** [comment]
> I agree, I have an issues with replit too (and with stackblitz). I would be appreciative of your contribution, but I should be the owner of the sandboxes to have ability to manage it in the feature.
> 
> If you have some advanced examples you could share it as a github repo, to make it possible to propose some feature changes by a PR. We could add this kind of links to examples page too.
> 
> I will rewrite the current links today.

#564 PR. All you need is to fork one csb and change repl link to make you owner. Thanks! I'll definetely looking forward to contribute to this amazing state manager!

**Comment by artalar** [comment]
@rainyEra thank you!
Have you any feedback about the example clarity and complexity? Is the hello world example to simple or it is enough?
What do you think about this new version: https://codesandbox.io/s/reatom-react-hello-world-fgt6jn ?

**Comment by ptrtorain** [comment]
> @rainyEra thank you! Have you any feedback about the example clarity and complexity? Is the hello world example to simple or it is enough? What do you think about this new version: https://codesandbox.io/s/reatom-react-hello-world-fgt6jn ?

Looks super, especially with comments for juniors. After the first example, I couldn't really say anything about the tool. But after little hello world example I saw this one

```
const fetchIssues = reatomAsync(async (ctx, query: string) => {
  await sleep(250) // debounce
  const { items } = await api.fetchIssues(query, ctx.controller)
  return items
}, 'fetchIssues').pipe(
  withDataAtom([]),
  withAbort({ strategy: 'last-in-win' }),
  withRetry({
    onReject(ctx, error: any, retries) {
      // return delay in ms or -1 to prevent retries
      return error?.message.includes('rate limit')
        ? 100 * Math.min(500, retries ** 2)
        : -1
    },
  }),
)
```
I was hooked by it's beauty...Wow. Also, there's fun story how I found this repository. I was working on two projects with Jotai and Rematch. I was needed to refresh my memories and google rematch docs, but I somehow mistyped "reatom" instead of "rematch" and found Reatom.😄

**Comment by artalar** [comment]
All links updated to codesandbox. Btw, in the base `reatomAsync` example from the main page `withCache` added.
