### ISSUE TITLE
ctx.call?

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#576]
An effect description could be much clear with a new `ctx.call` method, which is a simple wrapper around `ctx.schedule`: `call = (effect, ...params) => ctx.schedule(() => effect(...params))`, it allows an user to write async code directly in an action.

```ts
export const fetchData = action(async, (ctx, page) => {
  // a little bit ugly
  const data = await ctx.schedule(() => api.getData(page));
  // obvious and simple
  const data = await ctx.call(api.getData, page);
});
```

```ts
export const fetchData = action(async, (ctx) => {
  // more code
  const page = currentPageAtom(ctx, (state) => state + 1);
  const data = await ctx.schedule(() => api.getData(page));
  // less code (may be not a best example)
  const data = await ctx.call(api.getData, currentPageAtom(ctx, (state) => state + 1));
});
```

We can't change the existed `ctx.schedule` with the same semantic, as it already accepts the priority level by the second argument.

**Comment by BANOnotIT** [comment]
This approach implies that effect is bound to what it needs. Specifically that `getData` is bound to `api` already. That's not always the case and in my experience explicit binding is worse then direct call.

**Comment by artalar** [comment]
Ok, let's stay API simplier

P.S. this API is not friendly for a methods of a class. If the callback need `this`, the API will broke it. So...
