### ISSUE TITLE
Migrate our docs to starlight

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#588]
It looks like [starlight.astro.build](https://starlight.astro.build/) is a fancy enough to try it for our docs! It is not stable yet, but it has a simple update process (https://starlight.astro.build/getting-started/#updating-starlight), so I think it will work well.

A part of pages for the current docs is autogenerated by [this script](https://github.com/artalar/reatom/blob/v3/docs/sync-readme-to-pages.ts), stay it [there](https://github.com/artalar/reatom/blob/v3/docs/astro.config.mjs#L6).

[public](https://github.com/artalar/reatom/tree/v3/docs/public) contains a required to stay assets. Check out [styles/common.css](https://github.com/artalar/reatom/blob/v3/docs/public/styles/common.css), it includes a color variable which is good to stay to save our branding.

**Comment by crashmax-dev** [comment]
Great job @artalar :+1:
Issue to close?

**Comment by artalar** [comment]
Done!
