### ISSUE TITLE
Add animation properties to withStatusesAtom?

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#589]
An important part of a good UX for a loading indicator are start / end animations.

For example, a loading indicator could include a spinning or pulsating animation when it starts, indicating that the system is processing the requested task. As the task nears completion, the animation could gradually slow down or fade out, signifying that the loading process is coming to an end. These visual cues contribute to a positive user experience by providing a clear indication of progress, making it less flickering and minimizing perceived waiting time.

Do we need a general solution for that, like separate high-order atom with extra actions of start and end animations? Or we could start from additional properties for `withStatusesAtom` (`isEnteringAnimation: boolean`, `isLeavingAnimation: boolean`)?

**Comment by BANOnotIT** [comment]
I do think that animation can't be solved in "general" or "high order" fashion. It always requires high coupling with underlying animation solution thus I would suggest creating a guide on how to create custom `withAnimationController` instead of introducing the default one in general library.

**Comment by artalar** [comment]
I don't have enough production needs or motivation to build it.
