### ISSUE TITLE
Perf: Use undefined instead delete

### ISSUE THREAD

**Issue by belozer** [artalar/reatom#59]
Better for runtime optimizations

http://jsbench.github.io/#98e3e43d59ebeebc599a4bc25f38e791
![image](https://user-images.githubusercontent.com/1655916/64340409-c2455300-cfee-11e9-98aa-951201966ed8.png)

**But**
```
> a = { a: 140 }
{ a: 140 }
> a.a = undefined
undefined
> Object.keys(a)
[ 'a' ]
```

**Comment by artalar** [comment]
es6 Map is the best, i think
