### ISSUE TITLE
a difference between redux-saga and Reatom

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#591]
Let's investigate the differences between Redux-Saga and Reatom. What do we miss and what can we improve?

- [Sagas `take`](https://redux-saga.js.org/docs/api/#takepattern) is like [`take`](https://www.reatom.dev/packages/effects#take) + `await`.
- [Sagas `takeMaybe`](https://redux-saga.js.org/docs/api/#takemaybepattern) - is like [`take`](https://www.reatom.dev/packages/effects#take) WITHOUT `await`.
- [Sagas `takeEvery`](https://redux-saga.js.org/docs/api/#takemaybepattern) - is like `anAtom.onChange` / `anAction.onCall`.
- [Sagas `takeLatest`](https://redux-saga.js.org/docs/api/#takelatestpattern-saga-args) - is like `anAtom.onChange` / `anAction.onCall` + `reatomAsync().pipe(withAbort({ strategy: 'last-in-win' }))`.
- [Sagas `takeLeading`](https://redux-saga.js.org/docs/api/#takeleadingpattern-saga-args) - is like `anAtom.onChange` + `reatomAsync().pipe(withAbort({ strategy: 'first-in-win' }))`.
- [Sagas `call`](https://redux-saga.js.org/docs/api/#callfn-args) is a regular function call with a context + `await`.
- [Sagas `fork`](https://redux-saga.js.org/docs/api/#forkfn-args) is a regular function call with a context WITHOUT `await`.
- [Sagas `spawn`](https://redux-saga.js.org/docs/api/#spawnfn-args) have no analogy in Reatom. It should create a context without parent context abort propagation. Work in progress.
- [Sagas `join`](https://redux-saga.js.org/docs/api/#jointask) - is just `await` in Reatom.
- [Sagas `cancel`](https://redux-saga.js.org/docs/api/#canceltask) have no analogy in Reatom. It probably should looks like `getTopController(ctx).abort()`.
- [Sagas `cancelled`](https://redux-saga.js.org/docs/api/#cancelled) - is like `onCtxAbort`.

What is [our `takeNested`](https://www.reatom.dev/packages/effects#takenested) in redux-saga?

Two important notes.

1. Abortable context in Reatom currently works (starts) only by `reatomAsync` and `onConnect`. We will add a new general primitive for that in reatom/effects in a nearest time, what name should it have?
2. Sagas reacts to a [deep] children failure, which Reatom doesn't do. My current thoughts is that we should have built-in _transaction_ primitive, but I still not sure about a public API.

The main interesting thought - we already have a process context and could interact with a parents of the context by an abort controller manipulations. What we need is a transaction strategies to have an ability to interact with a children of the context.

![image](https://github.com/artalar/reatom/assets/27290320/07caee50-e112-4bcb-b7cb-4387fa0cecdf)

**Comment by ifeelBALANCED** [comment]
Here are some possible approaches in improving those areas:
Regarding spawn and cancel in Redux-Saga:
Spawn: You explained that this should create a context without parent context abort propagation. Therefore, in Reatom, it could be worthwhile to explore designs for a function that creates a new, independent context separate from the parent's context.
Cancel: You suggested the need for a mechanism similar to Saga’s cancel in Reatom. This would give you the ability to terminate a given context. An abort method called on a derived function of the parent context could serve this purpose.
takeNested in Redux-Saga is not a built-in effect in Redux-Saga. If you've been using it in your application, you might have a custom implementation or are using a library that extends Redux-Saga. For a corresponding implementation in Reatom, you would need to define what behavior you want from takeNested.
Regarding transaction strategies:
Built-in transactions could potentially allow for better management of effects that are interdependent or need to be handled as a single unit of work.
The public API for these transactions could potentially expose methods for beginning a transaction, adding effects to the transaction, committing the transaction, and rolling back the transaction. This would allow developers to group several effects together and control their lifecycle as a whole.
Naming a new general primitive for abortable context can depend heavily on its functionality and its purpose. The name should ideally make intuitive sense to developers who are not intimately familiar with the Reatom codebase. Something like createAbortContext, newAbortContext, or abortableContext might be good places to start, but the exact choice of name would need careful consideration.

**Comment by artalar** [comment]
added to docs
