### ISSUE TITLE
Documentation unfrendly for newbies

### ISSUE THREAD

**Issue by Akiyamka** [artalar/reatom#620]
Quite often we get feedback that the reatom documentation is frustrating.
This is a significant problem that scares off new users, we need to try to be closer to what they need.
Next, I will present suggestions for improvement based on the feedback:

- [ ] "Introduction" (main page), with few words about what reatom is, list of features with links, simple as possible hello world example.   
- [ ] "Getting started" - this mostly about boilerplate actions and code that user probably need to do:
  - Setup - Covers installation and bindings.
    - Installation
    - TypeScript
    - ESlint
    - React binding
    - Solid binding
    - Vue binding
  - Learning - Provides a few examples that explain core concepts and the main flow.
    - atom
    - action
    - context
    - Style guide and best practices 
  - Debugging
  - Testing - Discusses testing strategies
    
 - [ ] "Recipes" - Offers short examples that solve common use cases.
   -  Share component state
      - in react
      - in solid
      - in vue
   - Data fetching
     - Load data when component mounted 
     - Handing loading state
     - Handing errors
     - Parallel request
     - Sequential requests
     - Concurrent requests with canceling
   - Forms
     - Text input
     - Radio
     - Checkbox
     - Select
     - Validation
   - Undo / Redo
   - Data persisting
- [ ] "Examples" - Includes links to repositories with examples and pet projects.
- [ ] "Handbook" - Provides an in-depth exploration of reactive programming and the underlying features of Reatom.
- [ ] "Packages"
  - [Package]: Offers the raw API documentation for the specific package.
- REPL
- Compat

**Comment by artalar** [comment]
Not sure about the "Learning" section. Let it be a part of the handbook.

By the way, we should also consider other packages for presentation. If we only want to include raw API descriptions in the package README, then we should have more recipes.

**Comment by Akiyamka** [comment]
>  we should also consider other packages for presentation

Yes, I agree, after all, packages are not interesting in themselves, what is interesting is how they help to solve certain problems. Porposed set or Recipes it's only bare minimum

**Comment by artalar** [comment]
- **Introduction**: Provides an overview of the key features and includes a dumb example.
- **Getting Started**:
  - **Setup**: Covers installation and bindings.
  - **Learning**: Provides a few examples that explain core concepts and the main flow.
  - **Testing**: Discusses testing strategies.
  - **Deep Dive**: Introduces other packages related to the topic.
- **Recipes**: Offers short examples that solve common use cases.
- **Examples**: Includes links to repositories with examples and pet projects.
- **Handbook**: Provides an in-depth exploration of reactive programming and the underlying features of Reatom.
- **Packages**:
  - **[Package]**: Offers the raw API documentation for the specific package.
