### ISSUE TITLE
Rename reduce and reducer

### ISSUE THREAD

**Issue by belozer** [artalar/reatom#64]
## Reduce

`Reduce` mistakenly considered equivalent `reducer`. It about `big` -> `small`
Need use another name. Like `on` or `use` or `track`.

## Reducer
`reducer` in redux world takes actions and creates new data

But we **only** creates new data. 
Need use another name. Like `produce` or `producer`.

## Total proposal
**before**
```ts
declareAtom({}, reduce => [
  reduce(action, reducer)
])
```
**after**
```ts
declareAtom({}, on => [
  on(action, produce)
  // in russian: на действие произвести
])
```
on
```ts
declareAtom({}, on => [
  on(action, producer)
  // in russian: на действие производитель
])
```
track
```ts
declareAtom({}, track => [
  track(action, producer)
])
```
use
```ts
declareAtom({}, use => [
  use(action, producer)
])
```

**Comment by artalar** [comment]
`on` 👍

**Comment by artalar** [comment]
done
