### ISSUE TITLE
Match domain in eslint fix

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#662]
The common pattern in Reatom is to create a model in a fabric function, which should be started with the 'reatom' verb. It would be super handy to handle the model name and use it in the fix suggestion.

```ts
export const reatomMyModel = () => {
  const data = atom([]);
};
// -->
export const reatomMyModel = () => {
  const dataAtom = atom([], "MyModel.dataAtom");
};
```

```ts
const reatomMyModel = action(() => {
  const data = atom([]);
});
// -->
export const reatomMyModel = action(() => {
  const dataAtom = atom([], "MyModel.dataAtom");
}, "reatomMyModel");
```

**Comment by BANOnotIT** [comment]
If we go the way of getting naming data from the context then I would also vote for having name argument incorporated:

```ts
const reatomMyType = (...params, name?: string) => {
  return {
    someAtom: atom(..., `${name}.someAtom`)
  }
}
```

**Comment by BANOnotIT** [comment]
I think we'd better create a utility function that just generates names with model prefix. I have it in my project and I can give it to you together with usage examples.
