### ISSUE TITLE
Conversional commits

### ISSUE THREAD

**Issue by belozer** [artalar/reatom#74]
https://www.conventionalcommits.org/en/v1.0.0-beta.4/

Props

1. Readable commits for many peoples
2. "standart" using in many morepositories
3. Automaticly generate CHANGELOG via `lerna`
![image](https://user-images.githubusercontent.com/1655916/64500832-931d3300-d2c7-11e9-918c-f8fb9e6911e1.png)
4. Simple rules that are easy to remember
5. Ready linter for commits (https://www.npmjs.com/package/@commitlint/config-conventional)

**Comment by artalar** [comment]
Ok. Please add relative links and instructions to CONTRIBUTING.md
