### ISSUE TITLE
Revive package naming convention in contributing

### ISSUE THREAD

**Issue by BANOnotIT** [artalar/reatom#815]
There was a separate guide dedicated to entities naming in reatom. Package naming should be restored and put in contributing.md st least.

**Comment by ghost** [comment]
I failed to find the package naming convention in repo history. Could you give me the link or tell if there were any details to write about besides `npm`/`web`/`node` prefixes?

**Comment by BANOnotIT** [comment]
Context of the issue was discussed in chat: https://t.me/reatom_ru/64036

**Comment by BANOnotIT** [comment]
My interaction with convention document was in
https://github.com/artalar/reatom/commit/403a85153db12719dad06e3bc503d5a4a440c1da
