### ISSUE TITLE
Error DOMException: <ComponentName> unmount while Vite HMR

### ISSUE THREAD

**Issue by richvoronov** [artalar/reatom#839]
### What happened?

**What happened?**
I get DOM unmount error after updating React component files with Vite HMR

Context:
```
    "@vitejs/plugin-react-swc": "^3.6.0",
    "vite": "^5.1.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "@reatom/npm-react": "^3.8.6",
```

Reproduction:
1. Update component code, for example just write `console.log` somewhere
2. Save the file to have Vite update the files with HMR.
3. Then trigger `reatomAsync` and see the error in the console.

The error can be fixed by refreshing the page. So this is not a critical bug, but rather an annoying behavior

<img width="938" alt="image" src="https://github.com/artalar/reatom/assets/26653363/adb57380-a165-4cbc-8627-2fa182c9f671">

### Part

Package @reatom/npm-react

### Version

3.8.6

### Relevant log output

```shell
Uncaught (in promise) DOMException: SomeComponent unmount
```

**Comment by artalar** [comment]
Fixed in 43abda79f34526fb3329be96c4bb80ec64cf2881
