### ISSUE TITLE
Respect proposal-set-methods

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#864]
We should extends `reatomSet` ([docs](https://www.reatom.dev/package/primitives/#reatomset), [sources](https://github.com/artalar/reatom/blob/a6f9d4843e7e983d1a37b0c3a85214642a4d0925/packages/primitives/src/reatomSet.ts)) with the new https://github.com/tc39/proposal-set-methods:

- `Set.prototype.intersection(other)`
- `Set.prototype.union(other)`
- `Set.prototype.difference(other)`
- `Set.prototype.symmetricDifference(other)`
- `Set.prototype.isSubsetOf(other)`
- `Set.prototype.isSupersetOf(other)`
- `Set.prototype.isDisjointFrom(other)`

**Do not** write your own implementation of these methods. Instead, pass the arguments to the native methods. If a method doesn't exist (in an older environment), that is the responsibility of the library user.

Also, I propose to add a `toggle` method that accepts an element and adds it to the set if it does not exist, or removes it from the set if it does.

**Comment by debabin** [comment]
взял

**Comment by artalar** [comment]
Done in https://github.com/artalar/reatom/pull/866
