### ISSUE TITLE
@reatom/url: `globalThis.addEventListener is not a function`

### ISSUE THREAD

**Issue by Xelson** [artalar/reatom#884]
### What happened?

An error occurs when using `searchParamsAtom` in client componens of next.js:
```c
⨯ TypeError: globalThis.addEventListener is not a function
 ```
Apparently, this is happening here:
https://github.com/artalar/reatom/blob/b706d59c3f5aa91f77488fa2ce6dd97d9f324951/packages/url/src/index.ts#L111-L113
And the reason for this is that the code is executed in a server environment where there is no browser API

A code snippet with the reproducing:
https://stackblitz.com/edit/nextjs-eq9gsn?file=app%2Fpage.tsx,app%2FApp.tsx

### Part

Package @reatom/url

### Version

3.7.3

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
⨯ TypeError: globalThis.addEventListener is not a function
    at List (./src/pages/characters/ui/List.tsx:15:91)
digest: "3750509261"
```

**Comment by artalar** [comment]
Yeah, it is expected behaviour, please< follow this instructions for the fix: https://www.reatom.dev/package/url/#behavior
