### ISSUE TITLE
reatomCompoenent fails when is used with useAtomPromise inside

### ISSUE THREAD

**Issue by BANOnotIT** [artalar/reatom#890]
### What happened?

I wanted to use `useAtomPromise` to integrate with <Suspense> but when I use it inside `reatomComponent` render function, somehow it breaks out of <Suspense> and throws Promise in upper.

https://stackblitz.com/edit/stackblitz-starters-kspmls?file=src%2FTestComponent.tsx

### Part

Package @reatom/npm-react

### Version

3.8.10

### What browsers are you seeing the problem on?

Firefox

**Comment by artalar** [comment]
Fixed in https://github.com/artalar/reatom/commit/50075bd38604e378a7200d12abb6efb77c71f525 (https://github.com/artalar/reatom/releases/tag/npm-react-v3.9.0)
