### ISSUE TITLE
Rename package to reatom

### ISSUE THREAD

**Issue by belozer** [artalar/reatom#9]
The current name bad are the reports Manager. In Russian it is hard to read.
Name length in Russian `flaxom !== флаксом`

Proposal: **reatom**

Reasons:
**Re**usable **atom** (one atom for multi stores support)
**Re**active **atom** (combine, map)
**Re**active as good performance and **atom** as small bundle size
decla**re atom** as declarative state manager

Name length in Russian `reatom === реатом`

**Comment by artalar** [comment]
done
