### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by BataevDaniil** [artalar/reatom#937]
### What happened?

When i change [settingsAtom](https://github.com/artalar/reatom/blob/v3/packages/url/src/index.ts#L105) don't happen unsubscribe from [addListener](https://github.com/artalar/reatom/blob/v3/packages/url/src/index.ts#L95).
I think we should add method "destroy" to [hear](https://github.com/artalar/reatom/blob/v3/packages/url/src/index.ts#L6) when i can unsubscribe in [standard settings](https://github.com/artalar/reatom/blob/v3/packages/url/src/index.ts#L48)

### Part

Package @reatom/url

### Version
3.7.4

**Comment by artalar** [comment]
Solved in https://github.com/artalar/reatom/commit/742b30370ba86bed048ecbd9fddf4c02242cd2fe (https://github.com/artalar/reatom/releases/tag/url-v3.7.5)
