### ISSUE TITLE
'' What is a state manager '' link in core package's docs is broken

### ISSUE THREAD

**Issue by caio2983** [artalar/reatom#950]
### What happened?

The link circled in red is not working . It's redirecting to a 404 error page . The link should be https://www.reatom.dev/blog/what-is-state-manager and not https://www.reatom.dev/general/what-is-state-manager

![about](https://github.com/user-attachments/assets/1ae6ddc6-9a0e-42e0-856f-73ba1df672ce)

![errormanager](https://github.com/user-attachments/assets/fb994631-7da0-4f07-aeb7-35a6b07bd199)

### Part

Documentation site

**Comment by BANOnotIT** [comment]
fixed by #952
