### ISSUE TITLE
reatom/npm-react  error useAtom in production mode build 

### ISSUE THREAD

**Issue by dest86** [artalar/reatom#971]
### What happened?

If  use useAtom hook and compile project with webpack and ts-loader(esbuild-loader)  in  --mode production
component  throw error

`
TypeError: can't access property "type", r.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current is null`

`React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED?.ReactCurrentOwner?.current?.type` - optional chain removes from code after compile

https://stackblitz.com/edit/webpack-5-react-starter-57wcu7?file=src%2Fapp.tsx

### Part

Package @reatom/npm-react

### Version

3.10.0

**Comment by artalar** [comment]
This is Webpack problem https://github.com/webpack/webpack/issues/12960#issuecomment-1086272918
