### ISSUE TITLE
Typecheck broken after install @reatom/utils

### ISSUE THREAD

**Issue by karupoiss00** [artalar/reatom#983]
### What happened?

First line in `node_modules/@reatom/utils/build/index.d.ts` making reference on node js types. That brokes typecheck, which configured with DOM library. Please remove it.

### Part

Package @reatom/utils 3.11.0 @reatom/logger 3.8.4

**Comment by karupoiss00** [comment]
Same problem in @reatom/logger 3.8.4

**Comment by caio2983** [comment]
![typechecking](https://github.com/user-attachments/assets/c9f30ceb-0920-4f3b-aa2a-bc3bf35a33d5)


Is this the issue you're referring to?

**Comment by karupoiss00** [comment]
> ![typechecking](https://private-user-images.githubusercontent.com/82726583/390503642-c9f30ceb-0920-4f3b-aa2a-bc3bf35a33d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjcyMjAsIm5iZiI6MTczMjcyNjkyMCwicGF0aCI6Ii84MjcyNjU4My8zOTA1MDM2NDItYzlmMzBjZWItMDkyMC00ZjNiLWFhMmEtYmMzYmYzNWEzM2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE3MDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYTY1MmE1YTI3ZmFhOTAzMDc2N2MyZDViNTVhNWUwMjIxYWYyZDczZDE1YzZhNTY1OGJiZjMzMDBjOTUxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rLjqxzoQP2sz93F75dh-TQTLhV6QXxjWQZNdBMhZXRk)
> 
> Is this the issue you're referring to?

No, i am about reference to a nodejs environment types
![image](https://github.com/user-attachments/assets/285e1ca0-1e2a-4f0e-a32f-5335eb4bd6e1)

**Comment by karupoiss00** [comment]
@artalar

**Comment by artalar** [comment]
Fixed
