### ISSUE TITLE
Mocked fn-atom is still invoked

### ISSUE THREAD

**Issue by MOZGIII** [artalar/reatom#995]
### What happened?

```ts
import { createTestCtx } from "@reatom/testing";
import { atom } from "@reatom/framework";

const testAtom = atom<string>(() => {
  throw new Error("unreachable");
}, "testAtom");

ctx.mock(testAtom, "mocked");

console.log(ctx.get(testAtom));
```

Getting `Uncaught Error: unreachable`

### Part

Package @reatom/testing

### Version

@reatom/testing 3.4.7

@reatom/framework 3.4.56

### What browsers are you seeing the problem on?

Chrome

**Comment by artalar** [comment]
Fixed
