### ISSUE TITLE
onDisconnect doesn't get invoked with dynamically created atoms

### ISSUE THREAD

**Issue by val-o** [artalar/reatom#996]
### What happened?

When atom is dynamically created, onDisconnect hook never get called, even if atom loses it's sole subscriber 

Please see the [sandbox](https://codesandbox.io/p/sandbox/wandering-snow-f2gqwm)

Expected Console Output: 
computedFactoryAtom connected
dynamiclyCreatedAtom connected
somevalue_computed
computedFactoryAtom disconnected
_**dynamiclyCreatedAtom disconnected**_

Actual Console Output:
computedFactoryAtom connected
dynamiclyCreatedAtom connected
somevalue_computed
computedFactoryAtom disconnected

### Part

Package @reatom/core

### Version

> [3.4.56](https://www.npmjs.com/package/@reatom/framework/v/3.4.56)

**Comment by artalar** [comment]
Fixed
